name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install Node deps
        run: npm ci
      - name: Install Python deps
        run: pip install -r requirements.txt
      - name: Build CSS (PostCSS)
        run: npm run styles:docs
      - name: Build MkDocs site
        run: mkdocs build --strict
      - name: Minify HTML in site/
        run: npm run site:minify
      - name: Validate HTML with Nu HTML Checker (Docker)
        run: docker run --rm --entrypoint java -v "$PWD/site":/site ghcr.io/validator/validator:latest -jar /vnu.jar --skip-non-html --errors-only /site
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
